appstory6/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'appstory6'

urlpatterns = [
	# path('', views.addform, name="form"),
	# path('profile', views.profile, name="profile"),
	path('', views.aboutme, name='aboutme'),
	path('subscribe', views.subscribe, name='subscribe'),
	path('success', views.success, name='success'),
	path('validate', views.validate),
	path('subscribers', views.subscribers, name="subscribers"),
	path('sublist', views.getallsubs, name='sublist'),
	path('delsubs', views.delsubs)
] 

appstory9/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'appstory9'

urlpatterns = [
	path('searchbook', views.searchbook, name="search"),
	path('jsonfile', views.jsonfile, name="jsonfile"),
	path('increasefav', views.increasefav, name='increasefav'),
	path('decreasefav', views.decreasefav, name='decreasefav'),
	path('logout', views.logout_view , name='logout'),
]

story6/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
# from .views import logout_view

urlpatterns = [
	path('admin/', admin.site.urls),
    path('', include('appstory6.urls')),
    path('', include('appstory9.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
    ]


appstory6/models.py
from django.db import models
# from django.utils import timezone

# Create your models here.
# class Entry(models.Model):
# 	status  = models.CharField(max_length=200)
# 	created_at = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)

class Subscribe(models.Model):
	"""docstring for ClassName"""
	name = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	password = models.CharField(max_length=100)


	

appstory9/models.py
from django.db import models

# Create your models here.

appstory6/forms.py
from django import forms

# class Message_Form(forms.Form):
# 	status = forms.CharField(label= "Let me know what's up!", required=True)

class SubscribeForm(forms.Form):
	"""docstring for SubscribeForm"""
	name_attrs = {
		'type' : 'text',
		'class' : 'form-control',
		'placeholder' : 'Full Name',
	}

	email_attrs = {
		'type' : 'text',
		'class' : 'form-control',
		'placeholder' : 'Example: abcde@gmail.com'
	}

	pass_attrs = {
		'type' : 'password',
		'class' : 'form-control',
		'placeholder' : 'Password'
	}

	
	name = forms.CharField(max_length=100, widget = forms.TextInput(attrs=name_attrs))
	email = forms.EmailField(widget = forms.TextInput(attrs=email_attrs))
	password = forms.CharField(max_length=20, widget = forms.PasswordInput(attrs=pass_attrs))

appstory6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import SubscribeForm
from .models import Subscribe

# Create your views here.

# def addform(request):
#     form = Message_Form(request.POST or None)
#     response = {}
#     if(request.method == "POST"):
#         if (form.is_valid()):
#             status = request.POST.get('status')
#             Entry.objects.create(status=status)
#             print(status)
#             return HttpResponseRedirect('/')

#         else:
#             return render(request, "form.html", response)
#     else:
#     	status = Entry.objects.all()
#     	response['form'] = form
#     	response['status'] = status
#     	return render(request, 'form.html', response)
    
# def profile(request):
#     response = {}
#     return render(request, 'Profile.html', response)

def aboutme(request):
    response = {}
    return render(request, 'aboutme.html', response)

def subscribe(request):
    response = {}
    response['form'] = SubscribeForm()
    return render(request, 'subscribe.html', response)

def subscribers(request):
    return render(request, "sublist.html") 

@csrf_exempt
def validate(request):
    email = request.POST.get("email")
    data = {'not_valid': Subscribe.objects.filter(email__iexact=email).exists()
    }
    return JsonResponse(data)

def success(request):
    form = SubscribeForm(request.POST or None)
    if (form.is_valid()):
        data = form.cleaned_data
        newsubscriber = Subscribe(name=data['name'], password=data['password'], email=data['email'])
        newsubscriber.save()
        obdata = {'name': data['name']}
    return JsonResponse(obdata)

def getallsubs(request):
    data_json = serializers.serialize('json', Subscribe.objects.all())
    return HttpResponse(data_json, content_type='aplication/json')

@csrf_exempt
def delsubs(request):
    if 'email' in request.POST:
        email = request.POST['email']
        data = Subscribe.objects.filter(email=email)
        data.delete()
        return HttpResponseRedirect("/sublist")
    else:
        return HttpResponseRedirect("/sublist")



appstory9/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib.auth import authenticate, login, logout
import requests
import json

# Create your views here.
def searchbook(request):
	if request.user.is_authenticated:
		request.session['first_name'] = request.user.first_name
		request.session['last_name'] = request.user.last_name
		request.session['email'] = request.user.email
		request.session.get('counter', 0)
		for key, value in request.session.items():
			print('{} => {}'.format(key, value))
	return render(request, 'searchbook.html')

def jsonfile(request):
	searching =  request.GET.get('cari')	
	url = "https://www.googleapis.com/books/v1/volumes?q=" + searching
	data = requests.get(url).json()
	if request.user.is_authenticated:
		count = request.session.get('counter',0)
		request.session['counter'] = count
		for key, value in request.session.items():
			print('{} => {}'.format(key,value))
	return JsonResponse(data)

def logout_view(request):
	request.session.flush()
	logout(request)
	return HttpResponseRedirect('/searchbook')

def increasefav(request):
	print(dict(request.session))
	request.session['counter'] = request.session['counter'] + 1
	return HttpResponse(request.session['counter'], content_type='application/json')

def decreasefav(request):
	#print(dict(request.session))
	request.session['counter'] = request.session['counter'] - 1
	return HttpResponse(request.session['counter'], content_type='application/json')

appstory6/templates/Profile.html
<!-- <!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	{% include 'navbar.html' %}
	{% load static %}
	<link rel="stylesheet" href="{% static 'style.css' %}" />
	<script src="{% static 'aboutme.js' %}"></script>
	<style type="text/css">
		body{background: linear-gradient(to top, #ff33cc 0%, #6666ff 100%);}
		hr{border-color: black; opacity: 0.2;}
		.container{width: 100%}
		.row{padding: 10px;}
		.col-sm-12 h1,h3{ color: #000066; }
		.img{ display: block; margin: auto; }
	</style>
</head>

<body>
	<div id="overlayer"></div>
<span class="loader">
  <span class="loader-inner"></span>
</span>
	<div class="container">
		<div class="row">
			<div class="col-sm-12" style="margin-top: 10%;">
				<h1><b>MY PROFILE<b></h1>
				<hr>
			</div>
		</div>
		<div class="row" >
			<div class="col-sm-4" style="padding:20px;">
				<img src="https://i.imgur.com/JF95Vvc.png" class="img" style="width:200px;height:200px;">
			</div>
			<div class="col-sm-8" style="padding:10px; margin-top: 5%;">
				<h3>
					Nama: Azzahra Putri Ramadhanty<br>
					Date of Birth: Jakarta, January 5 1999<br>
					Hobby: Travelling, watching Youtube, etc.<br>
				</h3>
			</div>
		</div>
		<div class="link" style="margin-bottom: 17%;">
			<a href="{% url 'appstory6:form' %}" > Back to Home</a>
		</div>
		</div>
		</div>
	</div>


	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html> -->

appstory6/templates/aboutme.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <title>About Me</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'style.css' %}" />
  <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
  <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="{% static 'aboutme.js' %}"></script>

</head>

<body>
<div id="overlayer"></div>
<span class="loader">
  <span class="loader-inner"></span>
</span>
    <h1 style="margin-top: 5%; margin-bottom: 5%;text-align: center;"><b>WELCOME</b></h1>


    <div class="row" style="margin-bottom: 5%">
      <div class="col-sm-2" style="padding-left:12%">
        <img src="https://i.imgur.com/JF95Vvc.png" class="img" style="width:160px;height:160px;">
      </div>
      <div class="col-sm-8" style="padding-left:10%;margin-top: 1%">
        <h3 id="content">
          Nama: Azzahra Putri Ramadhanty<br>
          Date of Birth: Jakarta, January 5 1999<br>
          Hobby: Travelling, watching Youtube, etc.
        </h3>
        <a href="{% url 'appstory6:subscribe' %}" class="btn btn-dark" role="button" style="">Subscribe</a>
        <a href="{% url 'appstory6:subscribers' %}" class="btn btn-dark" role="button" style="margin: 10px;">Check Out Subscribers</a>
        <a href="{% url 'appstory9:search' %}" class="btn btn-dark" role="button" style="">Search Books</a>
      </div>

    </div>

  <div class="accordion">
    <button class="accordion-toggle">Aktivitas</button>
    <div class="accordion-content">
        <p>
          <ul>
          <li>Studying computer science in Fasilkom UI as a 2nd year student</li>
          <li>Preparing for UIAW 2018 as Fasilkom's traditional dance contingent</li>
          <li>Preparing for COMPFEST 2019 as Internal Controller</li>
          <li>Preparing for CGT in Action: Chapter 1 as VPIC of Bazaar&Food</li>
        </ul>
        </p>
    </div>
    <button class="accordion-toggle">Experiences</button>
    <div class="accordion-content">
      <p>
          <ul>
            <b>Organizational Experience</b>
              <li>Adkesma BEM Fasilkom UI</li>
              <li>Binari Fasilkom UI</li>
              <li>Mezzo Voices SMAN 3 Depok</li>
              <br>
              <b>Working Experience<br></b>
              <li>HRD of Fundraising COMPEST X 2018</li>
              <li>Head of Public Relations Wisgen 2018</li>
              <li>Vice Person of Fundraising PMB 2018</li>
              <li>Staff of Events OH Fasilkom 2018</li>
              <li>Staff of Bazaar&Food CGT 2018</li>
              <li>Staff of Public Relations Wisgan 2018</li>
              <li>Staff of Sponsorship Universiade UI 2017</li>
              <li>Staff of Public Relations Pemira Fasilkom 2017</li>
            </ul>
      </p>
    </div>
    <button class="accordion-toggle">Prestasi</button>
    <div class="accordion-content">
      <p>
          <ul>
            <li>Fasilkom UI's Traditional Dance Contingent UIAW 2018</li>
            <li>National Science Olympiad Participant Regency State 2014</li>
            <li>3rd Winner of National Grand Try Out by Yayasan Taruna Bangsa 2011</li>
          </ul>
      </p>
    </div>
  </div>

    <label style="margin-left:10%; margin-bottom: 10%;">
      <input type="checkbox" data-toggle="toggle" id="switch"> Turn on night mode
    </label>
</body>
</html>

appstory6/templates/form.html
<!-- <!DOCTYPE html>
<html>
<head>
	{% load crispy_forms_tags %}
	<title>How are you?</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	{% include 'navbar.html' %}
	{% load static %}
	<link rel="stylesheet" href="{% static 'style.css' %}" />
	<script src="{% static 'aboutme.js' %}"></script>
	<style type="text/css">
		body{background: linear-gradient(to top, #ff33cc 0%, #6666ff 100%);}
		.container{width: 100%}
		.col-sm-12 h1{text-align: center; font-size: 55px; color: #000066}
		.col-sm-12 h4{text-align: left; padding: 20px; padding-left: 0px}
		.registerbtn {
		    background-color: #622569;
		    color: white;
		    padding: 10px;
		    margin: 8px 0;
		    border-radius: 4px;
		    border-color: #622569;
		    cursor: pointer;
		    width: 8%;
		    opacity: 0.9;}
		.registerbtn:hover {
		    opacity: 1;
		    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
		}
		@media screen and (max-width: 600px){
			.registerbtn{
				width: 30%;
			}
		}
</style>
</head>

<body>
	<div id="overlayer"></div>
<span class="loader">
  <span class="loader-inner"></span>
</span>
	<div class="container">
		<div class="col-sm-12" style="margin-top: 20%; margin-bottom: 10%;">
			<h1><b>Hello, Apa Kabar?<b></h1>
		</div>
		<div class="col-sm-12" style="padding-left: 50px; padding-right: 45px;">
			<div class="form-group">
				<form id="form" method="POST" action="/">
					{% csrf_token %}
					{{ form|crispy }}
		    	<button type="submit" id="submit" class="registerbtn" value="submit">Submit</button>
				</form>
			</div>
			<a href="{% url 'appstory6:profile' %}"> See my profile here! </a>
		</div>
		<div class="col-sm-12" style="padding: 50px;">
			<h4><b>STATUS<b></h4>
			{% if status %}
				{% for event in status %}
	 			<div class="alert alert-dark" role="alert">
	 			<div>
	   				{{ event.status }} <br>
	   			</div>
	   			<div style="font-size: 12px;">
	   				{{ event.created_at }}
	   			</div>
	  			</div>
	  			{% endfor %}
  			{% else %}
                <h5>No schedule. Make a plan!</h5> 
                {% endif %}
			</div>
            <br>
	</div>
	</div>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html> -->

appstory6/templates/navbar.html
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    nav{
      background: linear-gradient(to bottom, #6600ff 0%, #000066 100%);
      border-color: linear-gradient(to bottom, #6600ff 0%, #000066 100%);
      margin: 0%;
    }
    a{
      color: white;
    }
    a:hover{
      color: #EE82EE;
    }
  </style>

</head>
<body>
<nav class="navbar navbar-default">
  	<div class="container-fluid">
		    <a href="{% url 'appstory6:form'%}">Home</a>
		   	<a href="{% url 'appstory6:profile'%}">Profile</a>
		   	<a href="{% url 'appstory6:aboutme'%}">About Me</a>
	    </ul>
  	</div>
</nav>
</body>
</html>

appstory6/templates/sublist.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title>List of Subsribers</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'style.css' %}" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
	<div class="row">
		<div class="col-sm-12">
			<h1>MY SUBSCRIBERS</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12" id="placeholder">
			
		</div>
	</div>

    <script>
        $(document).ready(function() {   
            $.ajax({
                url:"/subscribers",
                method: 'GET',
                dataType: 'html',
                success: function(data){
                    var pars = JSON.parse(data);
                    console.log(pars); 
                    for(i = 0; i< pars.length; i++) {
                        var card = "<div id =\"" + pars[i].fields.email + "\" class=\"card\" style=\"width: 30rem;\"> <div class=\"card-body\"><h5 class=\"card-title\">" + pars[i].fields.name + "</h5> <button type=\"button\" class=\"unsubscribe btn btn-dark\">Unsubscribe</button></div></div>";
                        $("#placeholder").append(card);
                    }
                    $(".unsubscribe").each(function() {
                        $(this).click(function () {
                            var emaildata = $(this).closest('.card').attr('id');
                            console.log(emaildata); 
                            $.ajax({
                                url:"/delsubs",
                                data: {email : emaildata},
                                method: 'POST',
                                dataType: 'json',
                                success: function() {
                                    swal({
                                        title: "Success",
                                        text: 'You have unsubscribed this website!',
                                        type: 'success',
                                        showConfirmButton: false,
                                        timer: 2500
                                        }).then(function() {
                                            window.location = "/subscribers"
                                        });   
                                    }
                                });
                        }
                        );
                    });
                }
            });
        });
    
    </script>
</body>
</html>

appstory6/templates/subscribe.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.min.css">
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.all.min.js"></script>
        <script src="{%static 'subscribe.js'%}"></script>
        <link rel="stylesheet" href="{% static 'style.css' %}" />


</head>
<body>
<!-- 	<div id="overlayer"></div>
		<span class="loader">
  			<span class="loader-inner"></span>
		</span> -->
	<div class="row">
		<div class="col-sm-12">
			<h2 style="text-align: center; margin-top: 4%">Fill this form to subscribe!</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<form method="POST">
				<div class="container center_div" style="width: 30%" id="form">
					{%csrf_token%}
					{{form}}
				<br>
				<button class="btn btn-dark" id="submit" disabled="disabled">Subscribe</button> 
				<br>
				<a href="{% url 'appstory6:aboutme'%}">Back to Home</a>
				</div>
			</form>
		</div>
	</div>
</body>
</html>

appstory6/templates/success.html
<!DOCTYPE html>
<html>
<head>
	{% load static%}
	<title>Thank You!</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.all.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>

</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.all.min.js"></script>
    <script>
        swal(
        'Success!',
        'Your data is recorded. Redirecting you back to home...',
        'success'
        ).then(function() {
            window.location = "{% url 'app_story6:aboutme' %}"
        });
    </script>
</body>
</html>

appstory9/templates/searchbook.html
<!DOCTYPE html>
<html>
<head>
	{%load static%}
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<script src="{% static 'searchbook.js' %}"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
	<style type="text/css">
		body {
			background: linear-gradient(to bottom, #66ffcc 0%, #ff99cc 100%);
		}
		.btn {
			background-color: black;
		}
	</style>

</head>
<body>
	<div class="container">
		<div class="row" style="margin-top: 3%">
	        {%if user.is_authenticated%}
	        <header class = "m-3" ">
	        	<a href= "{% url 'appstory9:logout'%}" style="text-transform:none; margin-top: 3%;">
         			<div class="left">
             			<img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
         			</div>
         			Log Out
         		</a>
	            <h3>Hello, {{ user.first_name }}!</h3>
	        </header>
	        {%else%}<header>
	        	<a href="{% url 'social:begin' 'google-oauth2' %}" style="text-transform:none">
         			<div class="left">
             			<img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
         			</div>
         		Login with Google
         	</a>
         	<br>
	        </header>
	        {%endif%}
		</div>
		<div row>
			<div class="text-center">
				<input type=text id="searchbar" class="textbox" style="margin-bottom: 2%;"> 
				<br>
				<button class="btn btn-dark" id="search" onclick="cari()">Search</button>
			</div>

	    	<div class="col-sm-12">
	    		<h4 id="fav"><i class='fa fa-star'style = 'color : #DA70D6'></i> {{ count }} </h4>
	    	</div>
	    	<div class="table-responsive">          
    	  	<table class="table" id="result" style="">
    		</table>
</div>
</body>
</html>